workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      when: always
    - when: never

.job_template: &ssh_key_configuration
  before_script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo "Host *" >> ~/.ssh/config
    - echo "  StrictHostKeyChecking no" >> ~/.ssh/config
    - echo "  CheckHostIP no" >> ~/.ssh/config
    - echo "  LogLevel ERROR" >> ~/.ssh/config
    - echo "  UserKnownHostsFile /dev/null" >> ~/.ssh/config

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  paths:
    - ~/.cache/pip/

stages:
  - mirror
  - default
  - all_pythons
  - docs


default:
  stage: default
  image: python:3.10
  before_script:
    - pip install tox
  script:
    - tox -e lint
    - tox -e py310


all_pythons:
  stage: all_pythons
  image: python:$PYTHON_VERSION
  before_script:
    - pip install tox
  script:
    - tox -e py${PYTHON_VERSION//./}
  parallel:
    matrix:
      - PYTHON_VERSION: ["3.8", "3.9", "3.11", "3.12"]

docs:
  stage: docs
  image: python:3.10
  before_script:
    - pip install tox
  script:
    - tox -e codespell


mirror-code:
  <<: *ssh_key_configuration
  stage: mirror
  script: |
    if [[ "${CI_COMMIT_REF_NAME}" == experiment* ]] || [[ "${CI_COMMIT_REF_NAME}" == AUTOML-* ]]
    then
        :
    else
      git branch -f ${CI_COMMIT_REF_NAME}
      git config remote.github.url >&- || git remote add github "$DESTINATION_REPO"
      git push -u github "${CI_COMMIT_REF_NAME}"
    fi
